from typing import Optional
from uuid import UUID

from sqlalchemy import ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base


class InspectionFinding(Base):
    """
    Stores findings generated by the DataGuard Inspector Agent.

    These findings represent dataset-level inspection issues such as:
    - missing values
    - duplicate records
    - added columns
    - removed columns
    - changed column types
    """

    inspection_id: Mapped[UUID] = mapped_column(
        ForeignKey(
            "inspectionruns.id",
            ondelete="CASCADE",
        ),
        nullable=False,
        index=True,
    )

    finding_type: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True,
    )

    severity: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        index=True,
    )

    message: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    evidence: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    column_name: Mapped[Optional[str]] = mapped_column(
        String(200),
        nullable=True,
        index=True,
    )

    expected_type: Mapped[Optional[str]] = mapped_column(
        String(50),
        nullable=True,
    )

    actual_type: Mapped[Optional[str]] = mapped_column(
        String(50),
        nullable=True,
    )

    inspection_run = relationship(
        "InspectionRun",
        back_populates="findings",
    )