"""add inspection runs and findings

Revision ID: 43a230dc2944
Revises: a6d9fc915d80
Create Date: 2026-09-07 18:12:06.283431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a230dc2944'
down_revision: Union[str, Sequence[str], None] = 'a6d9fc915d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspectionruns',
    sa.Column('dataset_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('highest_severity', sa.String(length=30), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspectionruns_dataset_path'), 'inspectionruns', ['dataset_path'], unique=False)
    op.create_index(op.f('ix_inspectionruns_highest_severity'), 'inspectionruns', ['highest_severity'], unique=False)
    op.create_index(op.f('ix_inspectionruns_status'), 'inspectionruns', ['status'], unique=False)
    op.create_table('inspectionfindings',
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('finding_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('column_name', sa.String(length=200), nullable=True),
    sa.Column('expected_type', sa.String(length=50), nullable=True),
    sa.Column('actual_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspectionruns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspectionfindings_column_name'), 'inspectionfindings', ['column_name'], unique=False)
    op.create_index(op.f('ix_inspectionfindings_finding_type'), 'inspectionfindings', ['finding_type'], unique=False)
    op.create_index(op.f('ix_inspectionfindings_inspection_id'), 'inspectionfindings', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_inspectionfindings_severity'), 'inspectionfindings', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspectionfindings_severity'), table_name='inspectionfindings')
    op.drop_index(op.f('ix_inspectionfindings_inspection_id'), table_name='inspectionfindings')
    op.drop_index(op.f('ix_inspectionfindings_finding_type'), table_name='inspectionfindings')
    op.drop_index(op.f('ix_inspectionfindings_column_name'), table_name='inspectionfindings')
    op.drop_table('inspectionfindings')
    op.drop_index(op.f('ix_inspectionruns_status'), table_name='inspectionruns')
    op.drop_index(op.f('ix_inspectionruns_highest_severity'), table_name='inspectionruns')
    op.drop_index(op.f('ix_inspectionruns_dataset_path'), table_name='inspectionruns')
    op.drop_table('inspectionruns')
    # ### end Alembic commands ###
