"""add etl findings

Revision ID: a6d9fc915d80
Revises: b8d599578eb4
Create Date: 2026-08-26 16:19:48.614580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d9fc915d80'
down_revision: Union[str, Sequence[str], None] = 'b8d599578eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etlfindings',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('finding_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=False),
    sa.Column('expected_average', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=False),
    sa.Column('upper_bound', sa.Float(), nullable=False),
    sa.Column('deviation', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('likely_area', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['etlruns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etlfindings_run_id'), 'etlfindings', ['run_id'], unique=False)
    op.create_index(op.f('ix_etlfindings_severity'), 'etlfindings', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etlfindings_severity'), table_name='etlfindings')
    op.drop_index(op.f('ix_etlfindings_run_id'), table_name='etlfindings')
    op.drop_table('etlfindings')
    # ### end Alembic commands ###
