"""add etl audit runs

Revision ID: b8d599578eb4
Revises: 4574906bff92
Create Date: 2026-08-26 14:44:25.910861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d599578eb4'
down_revision: Union[str, Sequence[str], None] = '4574906bff92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etlruns',
    sa.Column('pipeline_id', sa.String(length=100), nullable=False),
    sa.Column('dataset_id', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rows_input', sa.Integer(), nullable=True),
    sa.Column('rows_output', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checkpoint', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etlruns_dataset_id'), 'etlruns', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_etlruns_pipeline_id'), 'etlruns', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_etlruns_status'), 'etlruns', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etlruns_status'), table_name='etlruns')
    op.drop_index(op.f('ix_etlruns_pipeline_id'), table_name='etlruns')
    op.drop_index(op.f('ix_etlruns_dataset_id'), table_name='etlruns')
    op.drop_table('etlruns')
    # ### end Alembic commands ###
